CREATE CONSTRAINT faculty_id_unique IF NOT EXISTS FOR (f:FACULTY) REQUIRE f.id IS UNIQUE;
CREATE CONSTRAINT keyword_name_unique IF NOT EXISTS FOR (k:KEYWORD) REQUIRE k.name IS UNIQUE;
CREATE INDEX faculty_name_idx IF NOT EXISTS FOR (f:FACULTY) ON (f.name);
CREATE INDEX publication_id_idx IF NOT EXISTS FOR (p:PUBLICATION) ON (p.id);
